/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package org.example.Vlastne.NewGUI.Okno;

import OSPABA.Simulation;
import org.example.Vlastne.NewGUI.ISimulationDelegate;
import org.example.Vlastne.Ostatne.Konstanty;
import org.example.Vlastne.Ostatne.Prezenter;
import org.example.simulation.MySimulation;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;

/**
 *
 * @author Niko
 */
public class HlavneOkno extends javax.swing.JFrame implements ISimulationDelegate
{
    private MySimulation simulacia;
    private Thread simulacneVlakno;

    private Experiment experiment;

    private int rychlost;
    private boolean priebezneStatistikyVypisane;

    /**
     * Creates new form HlavneOkno
     */
    public HlavneOkno() {
        initComponents();
        this.inicializacia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        inputPocetReplikacii = new javax.swing.JTextField();
        inputNasada = new javax.swing.JTextField();
        inputPocetObsluznychMiest = new javax.swing.JTextField();
        inputPocetPokladni = new javax.swing.JTextField();
        buttonStart = new javax.swing.JButton();
        buttonPauza = new javax.swing.JButton();
        buttonStop = new javax.swing.JButton();
        sliderRychlost = new javax.swing.JSlider();
        labelRychlost = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelSimulacnyCas = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelAktualnaReplikacia = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelCelkovyCasSystem = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        labelPriemernyCasAutomat = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabulkaAgenti = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabulkaPokladne = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabulkaOkna = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        labelPriemernaDlzkaAutomat = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        labelDlzkaAutomat = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        labelCelkovyPriemernyCasAutomat = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        labelCelkovaPriemernaDlzkaAutomat = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        labelCasPoslednyOdchod = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        labelPocetObsluzenych = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        labelPriemernyCasOkno = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        labelDlzkaOkno = new javax.swing.JLabel();
        labelPriemernaDlzkaOkno = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        labelCelkovyPriemernyCasOkno = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        labelCelkovaPriemernaDlzkaOkno = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabulkaCelkovePokladne = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabulkaCelkoveOkna = new javax.swing.JTable();
        jLabel29 = new javax.swing.JLabel();
        labelVytazenieAutomat = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        labelCelkoveVytazenieAutomat = new javax.swing.JLabel();
        panelExperiment = new javax.swing.JPanel();
        buttonExperimentStart = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        labelExperimentAktualnaReplikacia = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        labelExperimentPocetOkien = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        labelExperimentPocetPokladni = new javax.swing.JLabel();
        panelGraf = new javax.swing.JPanel();
        buttonExperimentStop = new javax.swing.JButton();
        checkBoxPrestavka = new javax.swing.JCheckBox();
        checkBoxZvysenyTok = new javax.swing.JCheckBox();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel1.setText("Pocet replikacii:");

        jLabel2.setText("Nasada (prazdne pre nahodnu nasadu):");

        jLabel3.setText("Pocet obsluznych miest:");

        jLabel4.setText("Pocet pokladni:");

        buttonStart.setText("Start");
        buttonStart.setMaximumSize(new java.awt.Dimension(72, 50));
        buttonStart.setMinimumSize(new java.awt.Dimension(72, 50));
        buttonStart.setPreferredSize(new java.awt.Dimension(72, 50));
        buttonStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonStartMouseClicked(evt);
            }
        });

        buttonPauza.setText("Pauza");
        buttonPauza.setMaximumSize(new java.awt.Dimension(72, 50));
        buttonPauza.setMinimumSize(new java.awt.Dimension(72, 50));
        buttonPauza.setPreferredSize(new java.awt.Dimension(72, 50));
        buttonPauza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonPauzaMouseClicked(evt);
            }
        });

        buttonStop.setText("Stop");
        buttonStop.setMaximumSize(new java.awt.Dimension(72, 50));
        buttonStop.setMinimumSize(new java.awt.Dimension(72, 50));
        buttonStop.setPreferredSize(new java.awt.Dimension(72, 50));
        buttonStop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonStopMouseClicked(evt);
            }
        });

        sliderRychlost.setMajorTickSpacing(250);
        sliderRychlost.setMaximum(2000);
        sliderRychlost.setMinorTickSpacing(10);
        sliderRychlost.setPaintLabels(true);
        sliderRychlost.setPaintTicks(true);
        sliderRychlost.setSnapToTicks(true);
        sliderRychlost.setToolTipText("Rychlost");
        sliderRychlost.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sliderRychlostMouseReleased(evt);
            }
        });

        labelRychlost.setText("n/a");
        labelRychlost.setMaximumSize(new java.awt.Dimension(40, 16));
        labelRychlost.setMinimumSize(new java.awt.Dimension(40, 16));
        labelRychlost.setPreferredSize(new java.awt.Dimension(40, 16));

        jLabel6.setText("Simulacny cas:");

        labelSimulacnyCas.setText("n/a");
        labelSimulacnyCas.setMaximumSize(new java.awt.Dimension(100, 16));
        labelSimulacnyCas.setMinimumSize(new java.awt.Dimension(100, 16));
        labelSimulacnyCas.setPreferredSize(new java.awt.Dimension(100, 16));

        jLabel8.setText("Aktualna replikacia:");

        labelAktualnaReplikacia.setText("n/a");

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Celkove statistiky:");

        jLabel7.setText("Priemerny cas v systeme:");

        labelCelkovyCasSystem.setText("n/a");

        jLabel9.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Statistiky aktualnej replikacie:");

        jLabel10.setText("Priemerny cas vo fronte pred automatom:");

        labelPriemernyCasAutomat.setText("n/a");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Tabulka agenti:");

        tabulkaAgenti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Typ", "Stav", "Prichod system", "Front automat", "Front obsluzne miesto", "Front pokladna", "Vyzdvihovanie tovaru"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabulkaAgenti);
        if (tabulkaAgenti.getColumnModel().getColumnCount() > 0) {
            tabulkaAgenti.getColumnModel().getColumn(0).setMaxWidth(40);
            tabulkaAgenti.getColumnModel().getColumn(1).setMaxWidth(60);
        }

        tabulkaPokladne.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Obsadenost", "Vytazenie", "Dlzka front", "Priemerna dlzka front", "Priemerne cakanie front", "Prestavka", "Nahrada"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabulkaPokladne);
        if (tabulkaPokladne.getColumnModel().getColumnCount() > 0) {
            tabulkaPokladne.getColumnModel().getColumn(0).setMaxWidth(40);
            tabulkaPokladne.getColumnModel().getColumn(1).setPreferredWidth(100);
            tabulkaPokladne.getColumnModel().getColumn(1).setMaxWidth(100);
            tabulkaPokladne.getColumnModel().getColumn(2).setMaxWidth(80);
            tabulkaPokladne.getColumnModel().getColumn(3).setMaxWidth(110);
            tabulkaPokladne.getColumnModel().getColumn(6).setMaxWidth(55);
            tabulkaPokladne.getColumnModel().getColumn(7).setMaxWidth(55);
        }

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Tabulka obsluzni zamestnanci:");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Tabulka pokladne:");

        tabulkaOkna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Typ", "Obsadenost", "Vytazenie"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tabulkaOkna);

        jLabel11.setText("Priemerna dlzka frontu pred automatom:");

        labelPriemernaDlzkaAutomat.setText("n/a");

        jLabel15.setText("Aktualna dlzka frontu pred automatom:");

        labelDlzkaAutomat.setText("n/a");

        jLabel16.setText("Priemerny cas vo fronte pred automatom:");

        labelCelkovyPriemernyCasAutomat.setText("n/a");

        jLabel17.setText("Priemerna dlzka frontu pred automatom:");

        labelCelkovaPriemernaDlzkaAutomat.setText("n/a");

        jLabel18.setText("Priemerny cas posledneho odchodu:");

        labelCasPoslednyOdchod.setText("n/a");

        jLabel19.setText("Priemerny pocet obsluzenych zakaznikov:");

        labelPocetObsluzenych.setText("n/a");

        jLabel20.setText("Priemerny cas vo fronte pred obsluhou:");

        labelPriemernyCasOkno.setText("n/a");

        jLabel21.setText("Priemerna dlzka frontu pred obsluhou:");

        jLabel22.setText("Aktualna dlzka frontu pred obsluhou:");

        labelDlzkaOkno.setText("n/a");

        labelPriemernaDlzkaOkno.setText("n/a");

        jLabel23.setText("Priemerny cas vo fronte pred obsluhou:");

        labelCelkovyPriemernyCasOkno.setText("n/a");

        jLabel24.setText("Priemerna dlzka frontu pred obsluhou:");

        labelCelkovaPriemernaDlzkaOkno.setText("n/a");

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Tabulka obsluzni zamestnanci:");

        tabulkaCelkovePokladne.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Vytazenie", "Priemerna dlzka front", "Priemerne cakanie front"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tabulkaCelkovePokladne);
        if (tabulkaCelkovePokladne.getColumnModel().getColumnCount() > 0) {
            tabulkaCelkovePokladne.getColumnModel().getColumn(0).setMaxWidth(40);
            tabulkaCelkovePokladne.getColumnModel().getColumn(1).setMaxWidth(70);
        }

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Tabulka pokladne:");

        tabulkaCelkoveOkna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Typ", "Vytazenie"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tabulkaCelkoveOkna);

        jLabel29.setText("Vytazenie automatu:");

        labelVytazenieAutomat.setText("n/a");

        jLabel30.setText("Priemerne vytazenie automatu:");

        labelCelkoveVytazenieAutomat.setText("n/a");

        panelExperiment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelExperiment.setMaximumSize(new java.awt.Dimension(985, 288));
        panelExperiment.setMinimumSize(new java.awt.Dimension(985, 288));

        buttonExperimentStart.setText("Experiment");
        buttonExperimentStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExperimentStartActionPerformed(evt);
            }
        });

        jLabel25.setText("Aktualna replikacia:");

        labelExperimentAktualnaReplikacia.setText("n/a");

        jLabel28.setText("Pocet obsluznych miest:");

        labelExperimentPocetOkien.setText("n/a");

        jLabel31.setText("Pocet pokladni:");

        labelExperimentPocetPokladni.setText("n/a");

        panelGraf.setEnabled(false);
        panelGraf.setFocusable(false);
        panelGraf.setMaximumSize(new java.awt.Dimension(828, 270));
        panelGraf.setMinimumSize(new java.awt.Dimension(828, 270));
        panelGraf.setPreferredSize(new java.awt.Dimension(828, 270));
        panelGraf.setRequestFocusEnabled(false);
        panelGraf.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout panelGrafLayout = new javax.swing.GroupLayout(panelGraf);
        panelGraf.setLayout(panelGrafLayout);
        panelGrafLayout.setHorizontalGroup(
            panelGrafLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 828, Short.MAX_VALUE)
        );
        panelGrafLayout.setVerticalGroup(
            panelGrafLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        buttonExperimentStop.setText("Stop");
        buttonExperimentStop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonExperimentStopMouseClicked(evt);
            }
        });
        buttonExperimentStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExperimentStopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelExperimentLayout = new javax.swing.GroupLayout(panelExperiment);
        panelExperiment.setLayout(panelExperimentLayout);
        panelExperimentLayout.setHorizontalGroup(
            panelExperimentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExperimentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelExperimentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonExperimentStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelExperimentAktualnaReplikacia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelExperimentPocetOkien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelExperimentPocetPokladni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonExperimentStop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelGraf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelExperimentLayout.setVerticalGroup(
            panelExperimentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExperimentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelExperimentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelExperimentLayout.createSequentialGroup()
                        .addComponent(panelGraf, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(panelExperimentLayout.createSequentialGroup()
                        .addComponent(buttonExperimentStart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonExperimentStop)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelExperimentAktualnaReplikacia)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelExperimentPocetOkien)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelExperimentPocetPokladni)
                        .addGap(59, 59, 59))))
        );

        checkBoxPrestavka.setText("Prestavka");
        checkBoxPrestavka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxPrestavkaActionPerformed(evt);
            }
        });

        checkBoxZvysenyTok.setText("Zvyseny vstupny tok");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(filler2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputPocetPokladni, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputPocetObsluznychMiest, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputPocetReplikacii, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputNasada, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonPauza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(626, 626, 626)
                                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(buttonStop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(25, 25, 25)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(labelSimulacnyCas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(61, 61, 61)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(labelAktualnaReplikacia))
                                        .addGap(37, 37, 37)
                                        .addComponent(sliderRychlost, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(labelRychlost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(checkBoxPrestavka)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(checkBoxZvysenyTok)))
                        .addGap(49, 49, 49))
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(filler3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addComponent(panelExperiment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                                            .addComponent(labelPriemernyCasAutomat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(labelPriemernaDlzkaAutomat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelDlzkaAutomat, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelVytazenieAutomat, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 942, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelPriemernyCasOkno, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(39, 39, 39)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelPriemernaDlzkaOkno, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelDlzkaOkno, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(labelCelkovyCasSystem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(labelCelkovyPriemernyCasAutomat))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(labelCelkovaPriemernaDlzkaAutomat, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelCelkoveVytazenieAutomat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelCasPoslednyOdchod, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelPocetObsluzenych, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(labelCelkovyPriemernyCasOkno, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(labelCelkovaPriemernaDlzkaOkno, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9)))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(inputPocetReplikacii, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(inputNasada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(inputPocetObsluznychMiest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(inputPocetPokladni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(sliderRychlost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelSimulacnyCas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelAktualnaReplikacia))))))
                        .addGap(12, 12, Short.MAX_VALUE)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelRychlost, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(buttonPauza, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                    .addComponent(buttonStop, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                                .addComponent(buttonStart, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkBoxPrestavka)
                            .addComponent(checkBoxZvysenyTok))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel16)
                        .addComponent(jLabel17)
                        .addComponent(jLabel18)
                        .addComponent(jLabel24)
                        .addComponent(jLabel19)
                        .addComponent(jLabel30)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCelkovyCasSystem)
                    .addComponent(labelCelkovyPriemernyCasAutomat)
                    .addComponent(labelCelkovaPriemernaDlzkaAutomat)
                    .addComponent(labelCasPoslednyOdchod)
                    .addComponent(labelPocetObsluzenych)
                    .addComponent(labelCelkovyPriemernyCasOkno)
                    .addComponent(labelCelkovaPriemernaDlzkaOkno)
                    .addComponent(labelCelkoveVytazenieAutomat))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(panelExperiment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel15)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPriemernyCasAutomat)
                    .addComponent(labelPriemernaDlzkaAutomat)
                    .addComponent(labelDlzkaAutomat, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPriemernyCasOkno)
                    .addComponent(labelDlzkaOkno)
                    .addComponent(labelPriemernaDlzkaOkno)
                    .addComponent(labelVytazenieAutomat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );

        inputPocetReplikacii.getAccessibleContext().setAccessibleName("inputPocetReplikacii");
        inputNasada.getAccessibleContext().setAccessibleName("inputNasada");
        inputPocetObsluznychMiest.getAccessibleContext().setAccessibleName("inputPocetObsluznychMiest");
        inputPocetPokladni.getAccessibleContext().setAccessibleName("inputPocetPokladni");
        buttonStart.getAccessibleContext().setAccessibleName("buttonStart");
        buttonPauza.getAccessibleContext().setAccessibleName("buttonPauza");
        buttonStop.getAccessibleContext().setAccessibleName("buttonStop");
        sliderRychlost.getAccessibleContext().setAccessibleName("sliderRychlost");
        labelRychlost.getAccessibleContext().setAccessibleName("labelRychlost");
        labelSimulacnyCas.getAccessibleContext().setAccessibleName("labelSimulacnyCas");
        labelAktualnaReplikacia.getAccessibleContext().setAccessibleName("labelAktualnaReplikacia");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonStartMouseClicked
        try
        {
            this.inicializujSimulaciu();
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(HlavneOkno.this, "Neplatne zadane parametre simulacie!");
        }
    }//GEN-LAST:event_buttonStartMouseClicked

    private void sliderRychlostMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sliderRychlostMouseReleased
        this.rychlost = HlavneOkno.this.getRychlost();
        if (this.rychlost >= Konstanty.MAX_RYCHLOST)
        {
            HlavneOkno.this.labelRychlost.setText("MAX");
        }
        else
        {
            HlavneOkno.this.labelRychlost.setText(this.rychlost + "x");
        }

        if (HlavneOkno.this.simulacia != null)
        {
            this.simulacia.setRychlost(this.rychlost);
        }
    }//GEN-LAST:event_sliderRychlostMouseReleased

    private void buttonPauzaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPauzaMouseClicked
        this.toggleSimulaciaPozastavena();
    }//GEN-LAST:event_buttonPauzaMouseClicked

    private void buttonStopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonStopMouseClicked
        this.ukonciSimulaciu();
    }//GEN-LAST:event_buttonStopMouseClicked

    private void buttonExperimentStartActionPerformed(java.awt.event.ActionEvent evt) {
        try
        {
            this.inicializujExperiment();
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(HlavneOkno.this, "Neplatne zadane parametre experimentu!");
        }
    }

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void buttonExperimentStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExperimentStopActionPerformed
        if (this.experiment != null)
        {
            this.experiment.ukonciExperiment();
            this.experiment = null;
        }
    }//GEN-LAST:event_buttonExperimentStopActionPerformed

    private void buttonExperimentStopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonExperimentStopMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonExperimentStopMouseClicked

    private void checkBoxPrestavkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxPrestavkaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxPrestavkaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HlavneOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HlavneOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HlavneOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HlavneOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HlavneOkno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonExperimentStart;
    private javax.swing.JButton buttonExperimentStop;
    private javax.swing.JButton buttonPauza;
    private javax.swing.JButton buttonStart;
    private javax.swing.JButton buttonStop;
    private javax.swing.JCheckBox checkBoxPrestavka;
    private javax.swing.JCheckBox checkBoxZvysenyTok;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JTextField inputNasada;
    private javax.swing.JTextField inputPocetObsluznychMiest;
    private javax.swing.JTextField inputPocetPokladni;
    private javax.swing.JTextField inputPocetReplikacii;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelAktualnaReplikacia;
    private javax.swing.JLabel labelCasPoslednyOdchod;
    private javax.swing.JLabel labelCelkovaPriemernaDlzkaAutomat;
    private javax.swing.JLabel labelCelkovaPriemernaDlzkaOkno;
    private javax.swing.JLabel labelCelkoveVytazenieAutomat;
    private javax.swing.JLabel labelCelkovyCasSystem;
    private javax.swing.JLabel labelCelkovyPriemernyCasAutomat;
    private javax.swing.JLabel labelCelkovyPriemernyCasOkno;
    private javax.swing.JLabel labelDlzkaAutomat;
    private javax.swing.JLabel labelDlzkaOkno;
    private javax.swing.JLabel labelExperimentAktualnaReplikacia;
    private javax.swing.JLabel labelExperimentPocetOkien;
    private javax.swing.JLabel labelExperimentPocetPokladni;
    private javax.swing.JLabel labelPocetObsluzenych;
    private javax.swing.JLabel labelPriemernaDlzkaAutomat;
    private javax.swing.JLabel labelPriemernaDlzkaOkno;
    private javax.swing.JLabel labelPriemernyCasAutomat;
    private javax.swing.JLabel labelPriemernyCasOkno;
    private javax.swing.JLabel labelRychlost;
    private javax.swing.JLabel labelSimulacnyCas;
    private javax.swing.JLabel labelVytazenieAutomat;
    private javax.swing.JPanel panelExperiment;
    private javax.swing.JPanel panelGraf;
    private javax.swing.JSlider sliderRychlost;
    private javax.swing.JTable tabulkaAgenti;
    private javax.swing.JTable tabulkaCelkoveOkna;
    private javax.swing.JTable tabulkaCelkovePokladne;
    private javax.swing.JTable tabulkaOkna;
    private javax.swing.JTable tabulkaPokladne;
    // End of variables declaration//GEN-END:variables

    private void inicializacia()
    {
        this.priebezneStatistikyVypisane = true;
        this.inicializujSlider();
    }

    private void inicializujSlider()
    {
        this.sliderRychlost.setValueIsAdjusting(true);
        this.sliderRychlost.setValue(Konstanty.DEFAULT_RYCHLOST);
        this.sliderRychlost.setValueIsAdjusting(false);

        this.labelRychlost.setText(Konstanty.DEFAULT_RYCHLOST + "x");
        this.rychlost = this.sliderRychlost.getValue();
    }

    private void inicializujSimulaciu()
    {
        if (this.simulacia != null)
        {
            this.ukonciSimulaciu();
        }

        int pocetReplikacii = Integer.parseInt(this.inputPocetReplikacii.getText());
        boolean nasadaZadana = !this.inputNasada.getText().isEmpty();
        int nasada = (nasadaZadana ? Integer.parseInt(this.inputNasada.getText()) : -1);

        int pocetObsluznychMiest = Integer.parseInt(this.inputPocetObsluznychMiest.getText());
        int pocetPokladni = Integer.parseInt(this.inputPocetPokladni.getText());

        if (pocetObsluznychMiest < 3)
        {
            throw new RuntimeException("Pocet okien nemoze byt mensi ako 3!");
        }

        boolean prestavka = this.checkBoxPrestavka.isSelected();
        boolean zvysenyTok = this.checkBoxZvysenyTok.isSelected();

        this.simulacia = new MySimulation(nasada, nasadaZadana, Konstanty.TRVANIE_CAS_SEKUNDY,
            zvysenyTok, prestavka, pocetObsluznychMiest, pocetPokladni, this.rychlost);
        this.simulacia.pridajDelegata(this);

        this.simulacneVlakno = new Thread(() -> {
            if (this.rychlost >= Konstanty.MAX_RYCHLOST)
            {
                this.simulacia.setMaxSimSpeed();
            }
            else
            {
                this.simulacia.setSimSpeed(this.rychlost, Konstanty.DLZKA_PAUZY_S);
            }
            this.simulacia.simulate(pocetReplikacii);
        });
        this.simulacneVlakno.setName("Simulacia");
        this.simulacneVlakno.setDaemon(true);
        this.simulacneVlakno.setPriority(Thread.MAX_PRIORITY);
        this.simulacneVlakno.start();
    }

    private void ukonciSimulaciu()
    {
        if (this.simulacia != null)
        {
            this.simulacia.stopSimulation();
            this.simulacia.odoberDelegata(this);
            this.simulacia = null;
        }
    }

    private void toggleSimulaciaPozastavena()
    {
        if (this.simulacia != null)
        {
            if (!this.simulacia.isPaused())
            {
                this.simulacia.pauseSimulation();
            }
            else
            {
                this.simulacia.resumeSimulation();
            }
        }
    }

    private int getRychlost()
    {
        int zadanaRychlost = this.sliderRychlost.getValue();
        if (zadanaRychlost == 0)
        {
            return 1;
        }

        return zadanaRychlost;
    }

    private void resetujPriebezneStatistiky()
    {
        this.labelSimulacnyCas.setText("n/a");
        this.labelPriemernyCasAutomat.setText("n/a");
        this.labelPriemernaDlzkaAutomat.setText("n/a");
        this.labelDlzkaAutomat.setText("n/a");
        this.labelVytazenieAutomat.setText("n/a");
        this.labelPriemernyCasOkno.setText("n/a");
        this.labelPriemernaDlzkaOkno.setText("n/a");
        this.labelDlzkaOkno.setText("n/a");

        try
        {
            EventQueue.invokeAndWait(() -> {
                ((DefaultTableModel)this.tabulkaAgenti.getModel()).setRowCount(0);
                ((DefaultTableModel)this.tabulkaOkna.getModel()).setRowCount(0);
                ((DefaultTableModel)this.tabulkaPokladne.getModel()).setRowCount(0);
            });
        }
        catch (Exception ex)
        {
            throw new RuntimeException("Chyba pri resetovani priebeznych statistik!");
        }
    }

    private void inicializujExperiment()
    {
        if (this.experiment != null)
        {
            this.experiment.ukonciExperiment();
            this.experiment = null;
        }

        int pocetReplikacii = Integer.parseInt(this.inputPocetReplikacii.getText());
        boolean nasadaZadana = !this.inputNasada.getText().isEmpty();
        int nasada = (nasadaZadana ? Integer.parseInt(this.inputNasada.getText()) : -1);
        int pocetObsluznychMiest = Integer.parseInt(this.inputPocetObsluznychMiest.getText());

        boolean prestavka = this.checkBoxPrestavka.isSelected();
        boolean zvysenyTok = this.checkBoxZvysenyTok.isSelected();

        if (pocetObsluznychMiest < 3)
        {
            throw new RuntimeException("Pocet okien nemoze byt mensi ako 3!");
        }

        this.experiment = new Experiment(this.labelExperimentAktualnaReplikacia, this.panelGraf,
            Konstanty.MIN_POCET_POKLADNI, Konstanty.MAX_POCET_POKLADNI);
        this.labelExperimentPocetOkien.setText(String.valueOf(pocetObsluznychMiest));
        this.labelExperimentPocetPokladni.setText("<" + Konstanty.MIN_POCET_POKLADNI + ", " + Konstanty.MAX_POCET_POKLADNI + ">");
        this.experiment.spustiExperiment(pocetReplikacii, Konstanty.TRVANIE_CAS_SEKUNDY, pocetObsluznychMiest,
            nasada, nasadaZadana, zvysenyTok, prestavka);
    }

    @Override
    public void aktualizujSa(Simulation simulacneJadro, boolean celkoveStatistiky, boolean priebezneStatistiky)
    {
        MySimulation simulacia = (MySimulation)simulacneJadro;

        if (celkoveStatistiky)
        {
            Prezenter.aktualnaReplikacia(simulacia, this.labelAktualnaReplikacia);
            Prezenter.celkovyCasSystem(simulacia, this.labelCelkovyCasSystem);
            Prezenter.celkovyCasFrontAutomat(simulacia, this.labelCelkovyPriemernyCasAutomat);
            Prezenter.celkovaDlzkaFrontAutomat(simulacia, this.labelCelkovaPriemernaDlzkaAutomat);
            Prezenter.celkoveVytazenieAutomat(simulacia, this.labelCelkoveVytazenieAutomat);
            Prezenter.poslednyOdchod(simulacia, this.labelCasPoslednyOdchod);
            Prezenter.pocetObsluzenych(simulacia, this.labelPocetObsluzenych);
            Prezenter.celkovyCasFrontObsluzneMiesta(simulacia, this.labelCelkovyPriemernyCasOkno);
            Prezenter.celkovaDlzkaFrontObsluzneMiesta(simulacia, this.labelCelkovaPriemernaDlzkaOkno);
            Prezenter.tabulkaCelkoveObsluzneMiesta(simulacia, this.tabulkaCelkoveOkna);
            Prezenter.tabulkaCelkovePokladne(simulacia, this.tabulkaCelkovePokladne);
        }

        if (priebezneStatistiky && this.rychlost < Konstanty.MAX_RYCHLOST)
        {
            Prezenter.casFrontAutomat(simulacia, this.labelPriemernyCasAutomat);
            Prezenter.dlzkaFrontAutomat(simulacia, this.labelPriemernaDlzkaAutomat);
            Prezenter.aktualnaDlzkaFrontAutomat(simulacia, this.labelDlzkaAutomat);
            Prezenter.vytazenieAutomat(simulacia, this.labelVytazenieAutomat);
            Prezenter.casFrontOkno(simulacia, this.labelPriemernyCasOkno);
            Prezenter.dlzkaFrontObsluzneMiesta(simulacia, this.labelPriemernaDlzkaOkno);
            Prezenter.aktualnaDlzkaFrontOkno(simulacia, this.labelDlzkaOkno);
            Prezenter.tabulkaAgenti(simulacia, this.tabulkaAgenti);
            Prezenter.tabulkaObsluzneMiesta(simulacia, this.tabulkaOkna);
            Prezenter.tabulkaPokladne(simulacia, this.tabulkaPokladne);

            this.priebezneStatistikyVypisane = true;
        }
        else if (this.priebezneStatistikyVypisane)
        {
            this.resetujPriebezneStatistiky();
            this.priebezneStatistikyVypisane = false;
        }
    }

    @Override
    public void aktualizujSimulacnyCas(Simulation simulacneJadro)
    {
        MySimulation simulacia = (MySimulation)simulacneJadro;
        Prezenter.simulacnyCas(simulacia, this.labelSimulacnyCas);
    }
}
